name: Deploy Java Application

on:
  push:
    branches:
      - '**'

env:
  IMAGE_TAG: master-${{ github.run_number }}
  IMAGE_NAME: jzs175/spring-welcome-app
  CONTAINER_NAME: spring-welcome-app
  ENV_SCRIPT: env/env-${{ github.ref_name }}.sh
  ENV_DEPLOY_PATH: /var/app/welcome-app

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'

      - name: Building and Test with Maven
        run: |
          mvn -B package --file pom.xml

      - name: Push the JAR to local storage
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: target/welcome-app.jar
          retention-days: 1

      - name: The build has failed
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            🔴 <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">${{ github.repository }}</a> build error

  deploy-master:
    needs: [maven-build]
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4

      - name: Download built JAR-artifact
        uses: actions/download-artifact@v3
        with:
          name: jar-file
          path: ./target

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker MetaInfo
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.IMAGE_TAG }}            

      - name: Build Docker Image and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Upload the .env file on remote host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_PROD_HOST }}
          username: ${{ secrets.SSH_PROD_USERNAME }}
          password: ${{ secrets.SSH_PROD_PASSWORD }}
          port: ${{ secrets.SSH_PROD_PORT }}
          source: ${{ env.ENV_SCRIPT }}
          target: ${{ env.ENV_DEPLOY_PATH }}
          overwrite: true

      - name: Redeploy Docker
        uses: appleboy/ssh-action@v1.0.3
        env:
          ENV_DEPLOY_SCRIPT: ${{ env.ENV_DEPLOY_PATH }}/${{ env.ENV_SCRIPT }}
        with:
          host: ${{ secrets.SSH_PROD_HOST }}
          username: ${{ secrets.SSH_PROD_USERNAME }}
          password: ${{ secrets.SSH_PROD_PASSWORD }}
          port: ${{ secrets.SSH_PROD_PORT }}
          script_stop: true
          script: |
            source ${{ env.ENV_DEPLOY_SCRIPT }}
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            docker run -d --name ${{ env.CONTAINER_NAME }} --env-file ${{ env.ENV_DEPLOY_SCRIPT }} -p $TARGET_PORT:$TARGET_PORT ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: The deploy has failed
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            🔴🔴 <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">${{ github.repository }}</a> deploy error 

      - name: Good job!
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            🟢 <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">${{ github.repository }}</a> has been build and deployed on <b>PROD</b> successfully (docker tag=${{ env.IMAGE_TAG }})