name: Secrets Test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out the repository
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
          ALLMYVARS: ${{ toJSON(vars) }}
        run: |
          echo "$ALLMYSECRETS"
          echo "$ALLMYVARS"
        shell: bash

